app:
  oauth2:
    google:
      authorization-url: https://accounts.google.com/o/oauth2/v2/auth
      client-id: ${GOOGLE_CLIENT_ID}
      client-secret: ${GOOGLE_CLIENT_SECRET}
      redirect-uri: http://localhost:8080/authentication/oauth2/google/redirect
      access-token-url: https://oauth2.googleapis.com/token
      user-profile-url: https://www.googleapis.com/oauth2/v1/userinfo

spring:
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:local-test
    driver-class-name: org.h2.Driver
    username: sa

logging:
  level:
    com.eddicorp.javabackendboilerplate: debug